module.exports.data = [
  {
    address: "0x5A440E1bC93B7Fd7b65411CCBce101E97d4bA38A",
    metadata: {
      image:
        "ipfs://QmVqmA3dSEsNvTmG7WuCRjdRXmCrXAzS5EowKsJHyn2gRQ/ed-image.png",
      attributes: [
        { trait_type: "Department", value: "Department 8" },
        { trait_type: "Country", value: "Country 7" },
        { trait_type: "Case Number", value: "Case #14" },
        { trait_type: "Category", value: "Category 0" },
        { trait_type: "Subcategory", value: "Subcategory 5" },
        { trait_type: "Notice Content", value: "Notice Content 69" },
        { trait_type: "Action Link", value: "https://example.com/action3" },
        { trait_type: "Investigation Office", value: "Investigation Office 4" },
        { trait_type: "Issue Date", value: "2022-01-9" },
        { trait_type: "Last Date", value: "2022-02-8" },
      ],
    },
    // },
    // {
    //   address: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
    //   metadata: {
    //     department: "Department 7",
    //     country: "Country 1",
    //     caseNumber: "Case #124",
    //     category: "Category 4",
    //     subCategory: "Subcategory 9",
    //     noticeContent: "Notice Content 6",
    //     actionLink: "https://example.com/action2",
    //     imageLink: "https://example.com/image4.jpg",
    //     investigationOffice: "Investigation Office 3",
    //     issueDate: "2022-01-28",
    //     lastDate: "2022-02-21",
    //   },
    // },
    // {
    //   address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
    //   metadata: {
    //     department: "Department 7",
    //     country: "Country 3",
    //     caseNumber: "Case #293",
    //     category: "Category 4",
    //     subCategory: "Subcategory 6",
    //     noticeContent: "Notice Content 31",
    //     actionLink: "https://example.com/action9",
    //     imageLink: "https://example.com/image2.jpg",
    //     investigationOffice: "Investigation Office 3",
    //     issueDate: "2022-01-1",
    //     lastDate: "2022-02-0",
    //   },
    // },
    // {
    //   address: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
    //   metadata: {
    //     department: "Department 7",
    //     country: "Country 9",
    //     caseNumber: "Case #810",
    //     category: "Category 3",
    //     subCategory: "Subcategory 9",
    //     noticeContent: "Notice Content 65",
    //     actionLink: "https://example.com/action9",
    //     imageLink: "https://example.com/image4.jpg",
    //     investigationOffice: "Investigation Office 2",
    //     issueDate: "2022-01-25",
    //     lastDate: "2022-02-7",
    //   },
    // },
    // {
    //   address: "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65",
    //   metadata: {
    //     department: "Department 4",
    //     country: "Country 6",
    //     caseNumber: "Case #688",
    //     category: "Category 3",
    //     subCategory: "Subcategory 0",
    //     noticeContent: "Notice Content 27",
    //     actionLink: "https://example.com/action4",
    //     imageLink: "https://example.com/image2.jpg",
    //     investigationOffice: "Investigation Office 1",
    //     issueDate: "2022-01-25",
    //     lastDate: "2022-02-14",
    //   },
    // },
    // {
    //   address: "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc",
    //   metadata: {
    //     department: "Department 7",
    //     country: "Country 7",
    //     caseNumber: "Case #904",
    //     category: "Category 0",
    //     subCategory: "Subcategory 6",
    //     noticeContent: "Notice Content 75",
    //     actionLink: "https://example.com/action1",
    //     imageLink: "https://example.com/image0.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-20",
    //     lastDate: "2022-02-10",
    //   },
    // },
    // {
    //   address: "0x976EA74026E726554dB657fA54763abd0C3a0aa9",
    //   metadata: {
    //     department: "Department 3",
    //     country: "Country 5",
    //     caseNumber: "Case #205",
    //     category: "Category 2",
    //     subCategory: "Subcategory 6",
    //     noticeContent: "Notice Content 19",
    //     actionLink: "https://example.com/action5",
    //     imageLink: "https://example.com/image1.jpg",
    //     investigationOffice: "Investigation Office 3",
    //     issueDate: "2022-01-23",
    //     lastDate: "2022-02-7",
    //   },
    // },
    // {
    //   address: "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955",
    //   metadata: {
    //     department: "Department 5",
    //     country: "Country 9",
    //     caseNumber: "Case #417",
    //     category: "Category 0",
    //     subCategory: "Subcategory 2",
    //     noticeContent: "Notice Content 3",
    //     actionLink: "https://example.com/action4",
    //     imageLink: "https://example.com/image3.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-29",
    //     lastDate: "2022-02-25",
    //   },
    // },
    // {
    //   address: "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f",
    //   metadata: {
    //     department: "Department 9",
    //     country: "Country 3",
    //     caseNumber: "Case #839",
    //     category: "Category 4",
    //     subCategory: "Subcategory 3",
    //     noticeContent: "Notice Content 11",
    //     actionLink: "https://example.com/action0",
    //     imageLink: "https://example.com/image1.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-18",
    //     lastDate: "2022-02-18",
    //   },
    // },
    // {
    //   address: "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720",
    //   metadata: {
    //     department: "Department 3",
    //     country: "Country 4",
    //     caseNumber: "Case #756",
    //     category: "Category 0",
    //     subCategory: "Subcategory 2",
    //     noticeContent: "Notice Content 20",
    //     actionLink: "https://example.com/action0",
    //     imageLink: "https://example.com/image1.jpg",
    //     investigationOffice: "Investigation Office 4",
    //     issueDate: "2022-01-6",
    //     lastDate: "2022-02-5",
    //   },
    // },
    // {
    //   address: "0xBcd4042DE499D14e55001CcbB24a551F3b954096",
    //   metadata: {
    //     department: "Department 6",
    //     country: "Country 0",
    //     caseNumber: "Case #50",
    //     category: "Category 4",
    //     subCategory: "Subcategory 6",
    //     noticeContent: "Notice Content 69",
    //     actionLink: "https://example.com/action4",
    //     imageLink: "https://example.com/image3.jpg",
    //     investigationOffice: "Investigation Office 4",
    //     issueDate: "2022-01-16",
    //     lastDate: "2022-02-2",
    //   },
    // },
    // {
    //   address: "0x71bE63f3384f5fb98995898A86B02Fb2426c5788",
    //   metadata: {
    //     department: "Department 1",
    //     country: "Country 1",
    //     caseNumber: "Case #378",
    //     category: "Category 4",
    //     subCategory: "Subcategory 7",
    //     noticeContent: "Notice Content 74",
    //     actionLink: "https://example.com/action6",
    //     imageLink: "https://example.com/image3.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-27",
    //     lastDate: "2022-02-25",
    //   },
    // },
    // {
    //   address: "0xFABB0ac9d68B0B445fB7357272Ff202C5651694a",
    //   metadata: {
    //     department: "Department 2",
    //     country: "Country 1",
    //     caseNumber: "Case #345",
    //     category: "Category 3",
    //     subCategory: "Subcategory 3",
    //     noticeContent: "Notice Content 52",
    //     actionLink: "https://example.com/action0",
    //     imageLink: "https://example.com/image3.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-12",
    //     lastDate: "2022-02-17",
    //   },
    // },
    // {
    //   address: "0x1CBd3b2770909D4e10f157cABC84C7264073C9Ec",
    //   metadata: {
    //     department: "Department 8",
    //     country: "Country 6",
    //     caseNumber: "Case #21",
    //     category: "Category 0",
    //     subCategory: "Subcategory 3",
    //     noticeContent: "Notice Content 39",
    //     actionLink: "https://example.com/action2",
    //     imageLink: "https://example.com/image2.jpg",
    //     investigationOffice: "Investigation Office 4",
    //     issueDate: "2022-01-2",
    //     lastDate: "2022-02-10",
    //   },
    // },
    // {
    //   address: "0xdF3e18d64BC6A983f673Ab319CCaE4f1a57C7097",
    //   metadata: {
    //     department: "Department 3",
    //     country: "Country 3",
    //     caseNumber: "Case #718",
    //     category: "Category 1",
    //     subCategory: "Subcategory 5",
    //     noticeContent: "Notice Content 68",
    //     actionLink: "https://example.com/action8",
    //     imageLink: "https://example.com/image0.jpg",
    //     investigationOffice: "Investigation Office 4",
    //     issueDate: "2022-01-10",
    //     lastDate: "2022-02-14",
    //   },
    // },
    // {
    //   address: "0xcd3B766CCDd6AE721141F452C550Ca635964ce71",
    //   metadata: {
    //     department: "Department 8",
    //     country: "Country 4",
    //     caseNumber: "Case #949",
    //     category: "Category 3",
    //     subCategory: "Subcategory 1",
    //     noticeContent: "Notice Content 0",
    //     actionLink: "https://example.com/action0",
    //     imageLink: "https://example.com/image0.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-21",
    //     lastDate: "2022-02-7",
    //   },
    // },
    // {
    //   address: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30",
    //   metadata: {
    //     department: "Department 7",
    //     country: "Country 8",
    //     caseNumber: "Case #161",
    //     category: "Category 2",
    //     subCategory: "Subcategory 8",
    //     noticeContent: "Notice Content 33",
    //     actionLink: "https://example.com/action2",
    //     imageLink: "https://example.com/image0.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-21",
    //     lastDate: "2022-02-12",
    //   },
    // },
    // {
    //   address: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E",
    //   metadata: {
    //     department: "Department 4",
    //     country: "Country 5",
    //     caseNumber: "Case #89",
    //     category: "Category 2",
    //     subCategory: "Subcategory 4",
    //     noticeContent: "Notice Content 48",
    //     actionLink: "https://example.com/action2",
    //     imageLink: "https://example.com/image4.jpg",
    //     investigationOffice: "Investigation Office 4",
    //     issueDate: "2022-01-3",
    //     lastDate: "2022-02-3",
    //   },
    // },
    // {
    //   address: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0",
    //   metadata: {
    //     department: "Department 0",
    //     country: "Country 8",
    //     caseNumber: "Case #573",
    //     category: "Category 0",
    //     subCategory: "Subcategory 3",
    //     noticeContent: "Notice Content 11",
    //     actionLink: "https://example.com/action2",
    //     imageLink: "https://example.com/image0.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-5",
    //     lastDate: "2022-02-19",
    //   },
    // },
    // {
    //   address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199",
    //   metadata: {
    //     department: "Department 8",
    //     country: "Country 3",
    //     caseNumber: "Case #169",
    //     category: "Category 3",
    //     subCategory: "Subcategory 5",
    //     noticeContent: "Notice Content 73",
    //     actionLink: "https://example.com/action7",
    //     imageLink: "https://example.com/image1.jpg",
    //     investigationOffice: "Investigation Office 0",
    //     issueDate: "2022-01-3",
    //     lastDate: "2022-02-14",
    //   },
  },
];
